#!/bin/bash

unlock()
{
    test -d "$HOME/.config/yubikey-hotplug" || return 0
    [ $? -ne 0 ] && return 0
    if fgrep -qx $serial "$HOME/.config/yubikey-hotplug/serials" ; then
        logger -p kern.info "Unlocking screen for user $USER ($UID) due to Yubikey connect"
        loginctl unlock-sessions
    else
        logger -p kern.warn "Can't unlock screen for user $USER ($UID) due to Yubikey connect"
    fi
}

lock()
{
    test -d "$HOME/.config/yubikey-hotplug" || return 0
    [ $? -ne 0 ] && return 0
    logger -p kern.info "Locking screen for user $USER ($UID) due to Yubikey disconnect"
    loginctl lock-sessions
}

case "$1" in
    connect)
        serial=
            for ((i=0; i<5; i++)); do
                serial=`ykinfo -s -q`
                [ -n "$serial" ] && break
                sleep 1
            done
        if [ -z "$serial" ]; then
            logger -p kern.warn "Yubikey connected but unable to determine its serial number."
            exit 1
        fi
        logger -p kern.notice "Yubikey connected, serial #${serial}"
        unlock
        ;;
    disconnect)
        logger -p kern.notice "Yubikey disconnected"
        lock
        ;;
    *)
        echo "Usage: $0 (connect|disconnect)"
        ;;
esac
